pwatch.lo: /root/php-5.3.3/ext/pwatch/pwatch.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/php-5.3.3/ext/pwatch $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/php-5.3.3/ext/pwatch/pwatch.c -o pwatch.lo 
$(phplibdir)/pwatch.la: ./pwatch.la
	$(LIBTOOL) --mode=install cp ./pwatch.la $(phplibdir)

./pwatch.la: $(shared_objects_pwatch) $(PWATCH_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pwatch) $(PWATCH_SHARED_LIBADD)

